// Study desk content: formula sheet, glossary and flashcards for all worlds.

export interface Formula { name: string; tex: string; note: string; world: number; topic: string }
export const FORMULAS: Formula[] = [
  // Lecture I — process analysis
  { world: 2, topic: 'Process analysis', name: 'Resource capacity', tex: '\\text{capacity} = \\frac{60}{\\text{min per unit}} \\times \\text{machines}', note: 'Units per hour one resource can do (packing machine: 60/2 = 30 per hour).' },
  { world: 2, topic: 'Process analysis', name: 'Cycle time', tex: 'W_s = \\sum_{i} t_i', note: 'Time one unit needs through the line: sum of activity durations (knife line: 26 min).' },
  { world: 2, topic: 'Process analysis', name: 'Process capacity', tex: '\\min\\{\\text{cap}_1, \\dots, \\text{cap}_n\\}', note: 'Set by the bottleneck, the resource with the smallest capacity.' },
  { world: 2, topic: 'Process analysis', name: 'Throughput', tex: '\\text{th} = \\min\\{\\text{demand}, \\text{process capacity}\\}', note: 'Supply-constrained if demand ≥ capacity, else demand-constrained.' },
  { world: 2, topic: 'Process analysis', name: 'Utilization', tex: 'u = \\frac{\\text{actual production rate}}{\\text{maximum production rate}}', note: 'Packing machine: 25 / 30 = 83.33%. Only the bottleneck reaches 100%.' },
  { world: 2, topic: 'Process analysis', name: 'Processing time of a batch', tex: 't = \\frac{\\text{batch size}}{\\text{capacity}} \\times 3600\\ \\text{s}', note: 'Brewhouse: 0.1 L at 60 / 40 / 50 L/h → 6 / 9 / 7.2 s.' },
  // Lecture II ch. 3 — project selection
  { world: 3, topic: 'Project selection', name: 'Objective: revenue', tex: '\\max Z = \\sum_{i=1}^{I} e_i \\cdot X_i', note: 'Resources are sunk costs, so only revenue differs between plans. Chair vs. table: 9,500 at $X_C = 2$, $X_T = 3$.' },
  { world: 3, topic: 'Project selection', name: 'Resource capacity', tex: '\\sum_{i=1}^{I} a_{ij} \\cdot X_i \\le c_j \\quad \\forall j \\in \\{1, \\dots, J\\}', note: 'One constraint per resource: $X_C + 2X_T \\le 8$ for the large blocks (hop bales).' },
  { world: 3, topic: 'Project selection', name: 'Demand and integrality', tex: '\\begin{gathered} X_i \\le d_i \\quad \\forall i \\\\ X_i \\ge 0, \\; X_i \\text{ integer} \\end{gathered}', note: 'Integer = IP. Dropping integrality gives the LP relaxation (3 projects: 3,490.57 vs. 2,800).' },
  // Lecture II ch. 4 — aggregate planning
  { world: 4, topic: 'Aggregate planning', name: 'Inventory balance', tex: 'L_{t-1} + X_t - d_t = L_t, \\quad L_0 = 0', note: 'With $L_t \\ge 0$ it forces demand to be met in every period.' },
  { world: 4, topic: 'Aggregate planning', name: 'Capacity with overtime', tex: 'X_t \\le c + O_t', note: 'Overtime $O_t$ extends capacity at $k^o$ per unit.' },
  { world: 4, topic: 'Aggregate planning', name: 'Relevant costs', tex: 'Z = \\sum_{t=1}^{T} k^l L_t + \\sum_{t=1}^{T} k^o O_t', note: 'Chase 59,760 · Level 33,220 · Optimal 30,940 EUR.' },
  { world: 4, topic: 'Aggregate planning', name: 'Balance with backlog', tex: '\\begin{gathered} L_{t-1} - B_{t-1} + X_t - d_t = L_t - B_t \\\\ B_T = 0 \\end{gathered}', note: 'Backlog $B_t$ costs $k^b$ per unit and period ($k^b = 18$ → 30,700 EUR).' },
  { world: 4, topic: 'Aggregate planning', name: 'Backlog', tex: 'B_t = \\Big(\\sum_{\\tau \\le t} d_\\tau - \\sum_{\\tau \\le t} X_\\tau\\Big)^{+}', note: 'Cumulative demand minus cumulative production, if positive.' },
  // Lecture II ch. 5 — lot sizing
  { world: 5, topic: 'Lot sizing', name: 'Share of effective production time', tex: '\\frac{\\text{production time}}{\\text{setup time} + \\text{production time}}', note: 'Rises with the lot size: setup time is spread over more units.' },
  { world: 5, topic: 'Lot sizing', name: 'Setup forcing (big M)', tex: 'X_t \\le M \\cdot \\Gamma_t, \\quad \\Gamma_t \\in \\{0;1\\}', note: 'Production only after a setup; $M \\ge c$.' },
  { world: 5, topic: 'Lot sizing', name: 'Relevant costs', tex: 'Z = \\sum_{t=1}^{T} \\big(k^l L_t + s\\,\\Gamma_t\\big)', note: 'Lot-for-lot 1,000 · lot = capacity 900 · optimal 580 EUR.' },
  { world: 5, topic: 'Lot sizing', name: 'Shared capacity (multi-product)', tex: '\\sum_{i=1}^{I} a_i X_{it} \\le c \\quad \\forall t', note: 'Two products, $a_1 = a_2 = 1$ h/unit, $c = 150$ h → 995 EUR.' },
  // Tutorials 6–7 — stochastic variability and queues
  { world: 6, topic: 'Stochastic variability', name: 'Expected value', tex: 'E[X] = \\sum_i x_i \\cdot p(x_i)', note: 'Machines 1 and 2: E[X] = 35.6 s.' },
  { world: 6, topic: 'Stochastic variability', name: 'Variance and standard deviation', tex: '\\begin{gathered} V[X] = \\sum_i (x_i - E[X])^2 \\, p(x_i) \\\\ \\sigma = \\sqrt{V[X]} \\end{gathered}', note: 'Machine 1: $V[X] = 37.14\\ \\text{s}^2$, $\\sigma = 6.09$ s.' },
  { world: 6, topic: 'Stochastic variability', name: 'Coefficient of variation', tex: 'cv = \\frac{\\sigma}{E[X]}', note: 'Machine 1: 0.17 vs. machine 2: 0.10 → machine 1 is more variable.' },
  { world: 6, topic: 'Queues', name: 'Utilization', tex: '\\rho = \\frac{\\lambda}{\\mu}', note: 'Depends only on the means, not on variability.' },
  { world: 6, topic: 'Queues', name: 'Expected waiting time (single server)', tex: 'E[W_q] = \\frac{cv_a^2 + cv_s^2}{2} \\cdot \\frac{\\rho}{1-\\rho} \\cdot \\frac{1}{\\mu}', note: 'Exercise 7: $cv_a^2 = 0$, $cv_s^2 = 1.2$, $\\rho = 8/9$ → 384 min.' },
  { world: 6, topic: 'Queues', name: 'Cycle time', tex: 'E[W_s] = E[W_q] + \\frac{1}{\\mu}', note: '384 + 80 = 464 min.' },
  { world: 6, topic: "Queues", name: "Little's law", tex: 'E[L_s] = \\lambda \\cdot E[W_s]', note: '(60/90) × (464/60) = 5.16 workpieces.' },
  { world: 6, topic: 'Queues', name: 'Waiting guests', tex: 'E[L_q] = \\lambda \\cdot E[W_q]', note: "Little's law for the line only. Library: $\\frac{10}{60} \\cdot 25 = 4.17$ waiting on average." },
  { world: 6, topic: 'Stochastic variability', name: 'Scaling a random variable', tex: '\\begin{gathered} E[kX] = k\\,E[X] \\qquad V[kX] = k^2\\,V[X] \\\\ cv(kX) = cv(X) \\end{gathered}', note: 'Dice Bar: 3 EUR per beer → $E = 10.50$, $V = 26.25$, $cv = 0.49$.' },
];

export interface Term { term: string; def: string; world: number }
export const GLOSSARY: Term[] = [
  { world: 1, term: 'Operations management', def: 'Management and engineering approaches for effective planning of resources and activities in production and service systems and networks, from the strategic down to the control level.' },
  { world: 1, term: 'Production management', def: 'Management of business operations related to manufacturing goods.' },
  { world: 1, term: 'Service operations management', def: 'Management of business operations related to providing services.' },
  { world: 1, term: 'Procurement & supply chain management', def: 'Management of storage, transportation and delivery of goods along the supply chain.' },
  { world: 1, term: 'Operations planning', def: 'How to use capacity.' },
  { world: 1, term: 'Capacity planning', def: 'How to set capacity.' },
  { world: 1, term: 'Variability', def: 'Changes in volume or time due to uncertainty, time dependency or heterogeneity.' },
  { world: 1, term: 'Uncertainty', def: 'Deterministic (known in advance) vs. stochastic (random).' },
  { world: 1, term: 'Dynamics', def: 'Stationary (characteristics do not change over time) vs. time-dependent.' },
  { world: 1, term: 'Heterogeneity', def: 'Homogeneous (one kind) vs. heterogeneous (product variants, customer classes, resource types).' },
  { world: 2, term: 'Flow unit', def: 'What flows through the process: customers, data, material, cash.' },
  { world: 2, term: 'Capacity', def: 'Maximum number of units a resource can produce per period.' },
  { world: 2, term: 'Bottleneck', def: 'Resource with the smallest capacity; determines process capacity.' },
  { world: 2, term: 'Process capacity', def: 'Maximum amount the process can supply = minimum resource capacity.' },
  { world: 2, term: 'Throughput', def: 'Actual output rate = min(demand, process capacity).' },
  { world: 2, term: 'Cycle time', def: 'Time a flow unit needs through the process = sum of activity durations.' },
  { world: 2, term: 'Utilization', def: 'Actual production rate divided by maximum production rate.' },
  { world: 2, term: 'Supply-constrained', def: 'Demand exceeds process capacity; the bottleneck limits throughput.' },
  { world: 2, term: 'Demand-constrained', def: 'Process capacity exceeds demand; demand limits throughput.' },
  { world: 2, term: 'Balanced flow', def: 'All activities synchronized with the bottleneck activity.' },
  { world: 4, term: 'Aggregate planning', def: 'Decides production volume over time for aggregated product types with global capacities; trades off overtime and inventory holding.' },
  { world: 4, term: 'Chase strategy', def: 'Production equals demand in each period; capacity adapted by overtime; no inventory.' },
  { world: 4, term: 'Level strategy', def: 'Constant production volume (average demand); inventory rises and falls.' },
  { world: 4, term: 'Inventory holding costs', def: 'Cost of capital, depreciation, storage space and handling; $k^l$ per unit and period.' },
  { world: 4, term: 'Backlog', def: 'Demand fulfilled late: (cumulative demand − cumulative production)⁺; costs $k^b$ per unit and period; $B_T = 0$.' },
  { world: 4, term: 'Inventory balance equation', def: '$L_{t-1} + X_t - d_t = L_t$: stock at the end of t equals stock before plus production minus demand.' },
  { world: 5, term: 'Setup process', def: 'Preparation of a production system for its task (e.g. rinsing the kettle).' },
  { world: 5, term: 'Setup time', def: 'Time required for the setup; it reduces productive time.' },
  { world: 5, term: 'Setup costs', def: 'Personnel, material and ramp-up (opportunity) costs of a setup; $s$ per setup.' },
  { world: 5, term: 'Lot', def: 'The demand of several periods combined into one production run.' },
  { world: 5, term: 'Lot-for-lot', def: 'Produce exactly each period’s demand; no stock, a setup in every period with demand.' },
  { world: 3, term: 'Optimization model', def: 'Simplified mathematical representation of reality that reflects all alternatives, has a measurable objective and supports decisions.' },
  { world: 3, term: 'Parameter', def: 'Given input data of a model, e.g. $c_j$, $a_{ij}$, $e_i$, $d_i$.' },
  { world: 3, term: 'Decision variable', def: 'Value the model chooses, e.g. the project quantities $X_i$.' },
  { world: 3, term: 'Feasible solution', def: 'A plan that satisfies all constraints. Infeasible: at least one constraint is violated. Optimal: feasible and no feasible plan is better.' },
  { world: 3, term: 'Linear program (LP)', def: 'Linear objective and constraints, real-valued variables. Solved graphically or with the simplex algorithm.' },
  { world: 3, term: 'Integer program (IP)', def: 'Like an LP but with integer variables. Solved by complete enumeration, heuristics or branch and bound.' },
  { world: 3, term: 'LP relaxation', def: 'The IP without the integer constraints; its optimum is an upper bound (for maximization). Rounding it can be infeasible.' },
  { world: 3, term: 'Sunk costs', def: 'Costs already paid that do not change with the decision (the blocks, malt and hops in stock).' },
  { world: 6, term: 'Random variable', def: 'A quantity whose value is uncertain before it is observed, described by values $x_i$ and probabilities $p(x_i)$.' },
  { world: 6, term: 'Coefficient of variation', def: '$cv = \\sigma / E[X]$: spread relative to the mean; compares variability of quantities with different scales.' },
  { world: 6, term: 'Utilization (queue)', def: '$\\rho = \\lambda / \\mu$: share of time the server is busy. Depends only on the means.' },
  { world: 6, term: "Little's law", def: '$E[L_s] = th \\cdot E[W_s]$ in any stable system; in steady state $th = \\lambda$.' },
  { world: 6, term: 'Variability buffer', def: 'What absorbs a mismatch of supply and demand: inventory (early match), waiting / lead time (late match), capacity, or lost customers.' },
  { world: 6, term: 'Stable queue', def: 'A queue with $\\rho < 1$. With $\\rho \\ge 1$ the line grows without limit.' },
  { world: 5, term: 'Big M', def: 'A sufficiently large number ($M \\ge c$) in $X_t \\le M \\cdot \\Gamma_t$, linking production to the binary setup variable.' },
];

export interface Flashcard { id: string; front: string; back: string; world: number }
export const FLASHCARDS: Flashcard[] = [
  ...GLOSSARY.map((t, i) => ({ id: `g${i}`, front: t.term, back: t.def, world: t.world })),
  { id: 'q1', world: 1, front: 'Difference between time-dependent and stochastic demand?', back: 'Time-dependent = the pattern changes over time (dynamics), possibly fully known. Stochastic = random, not known in advance (uncertainty).' },
  { id: 'q2', world: 2, front: 'Resource capacity vs. process capacity vs. throughput?', back: 'Resource capacity: one station. Process capacity: min over stations. Throughput: min(demand, process capacity).' },
  { id: 'q3', world: 2, front: 'Effect of a parallel machine on cycle time and bottleneck?', back: 'Cycle time unchanged. Capacity of that station doubles; process capacity rises only if it was the bottleneck, and the bottleneck may move.' },
  { id: 'q5', world: 4, front: 'Chase vs. level vs. optimal cost in the lecture example?', back: 'Chase 59,760 EUR (only overtime) · Level 33,220 EUR (only inventory) · Optimal 30,940 EUR (inventory 26,620 + overtime 4,320).' },
  { id: 'q6', world: 4, front: 'When is the chase strategy optimal?', back: 'When overtime is not more expensive than holding a unit for one period ($k^o \\le k^l$): pre-producing never pays off.' },
  { id: 'q7', world: 4, front: 'What changes with backlog in the model?', back: 'New variable $B_t$ and cost $k^b$; balance $L_{t-1} - B_{t-1} + X_t - d_t = L_t - B_t$; and $B_T = 0$.' },
  { id: 'q8', world: 5, front: 'Lot sizing example: lot-for-lot, lot = capacity, optimal?', back: '1,000 EUR (10 setups) · 900 EUR (2 setups + 700 holding) · 580 EUR (setups in periods 1, 4, 8: 300 + 280).' },
  { id: 'q9', world: 5, front: 'How does $X_t \\le M \\cdot \\Gamma_t$ work?', back: '$\\Gamma_t = 0$ forces $X_t \\le 0$, so producing needs $\\Gamma_t = 1$. $\\Gamma_t = 1$ without production only adds cost $s$, so the optimum avoids it.' },
  { id: 'q10', world: 5, front: 'Effect of higher $s$ or higher $k^l$ on the number of setups?', back: 'Higher setup cost $s$ → fewer setups (bigger lots). Higher holding cost $k^l$ → more setups (smaller lots).' },
  { id: 'q11', world: 3, front: 'Chair vs. table: model and optimum?', back: '$\\max 1000X_C + 2500X_T$ s.t. $2X_C + 2X_T \\le 12$, $X_C + 2X_T \\le 8$, $X_C \\le 6$, $X_T \\le 3$, integer. Optimum $X_C = 2$, $X_T = 3$, $Z = 9{,}500$.' },
  { id: 'q12', world: 3, front: 'Solution approaches for LP vs. IP?', back: 'LP: graphical solution, simplex. IP: complete enumeration, heuristics, branch and bound.' },
  { id: 'q13', world: 6, front: 'Dice Bar (3 EUR per beer): E, V, σ, cv of the cost?', back: '$E = 10.50$ EUR, $V = 26.25$ EUR², $\\sigma = 5.12$ EUR, $cv = 0.49$.' },
  { id: 'q14', world: 6, front: 'Library queue: λ = 10/h, 1/µ = 5 min, $cv_a^2 = cv_s^2 = 1$?', back: '$\\rho = 5/6$, $E[W_q] = 25$ min, $E[W_s] = 30$ min, $E[L_s] = 5$.' },
  { id: 'q15', world: 6, front: 'Does more service variability raise utilization?', back: 'No. $\\rho = \\lambda / \\mu$ depends only on the means; variability raises the waiting time.' },
  { id: 'q4', world: 2, front: 'Knife line (8, 10, 5, 2, 1 min): bottleneck, process capacity, cycle time?', back: 'Grinding (10 min), 6 per hour, 26 minutes.' },
];
